"""Shared test fixtures and sample data."""

SAMPLE_RESUME = (
    "LALIT MANASINGH\n"
    "Full-Stack Developer\n"
    "manasinghlalit@gmail.com | +91 8249742970 | Pune, Maharashtra, India\n\n"
    "PROFESSIONAL SUMMARY\n"
    "Detail-oriented Full-Stack Developer with 2+ years of experience in building scalable,\n"
    "enterprise-grade web applications using Angular, .NET Core, and SQL.\n\n"
    "PROFESSIONAL EXPERIENCE\n"
    "Software Developer I, Johnson Controls (01/2023 – Present, Pune, India)\n"
    "- Developed a dynamic compliance report system using lazy-loaded Angular components and\n"
    "  paginated .NET APIs, reducing report load time by 70% across 2M+ records.\n"
    "- Built modular backend service classes using Repository Pattern and Dependency Injection.\n\n"
    "EDUCATION\n"
    "B.Tech in Computer Science, KIIT University (2023) — CGPA: 8.6/10\n\n"
    "TECHNICAL SKILLS\n"
    "Languages: C#, JavaScript, TypeScript, SQL\n"
    "Backend: .NET Core, RESTful APIs\n"
    "Frontend: Angular, React\n"
    "Databases: PostgreSQL, MySQL\n"
    "Tools: Git, Azure DevOps\n"
    "Methodologies: Agile, CI/CD, TDD\n"
)

SAMPLE_JD = (
    "Software Development Engineer (SDE II) — CloudSync Technologies\n\n"
    "Requirements:\n"
    "- 2-4 years of experience in software development\n"
    "- Strong proficiency in C# and .NET Core\n"
    "- Experience building RESTful APIs\n"
    "- Angular or React for frontend\n"
    "- SQL (PostgreSQL or MySQL)\n"
    "- Git, CI/CD, Agile\n\n"
    "Nice to have:\n"
    "- Docker and containerized deployments\n"
    "- Message queues (RabbitMQ, Azure Service Bus)\n"
    "- Unit testing frameworks (xUnit, NUnit)\n\n"
    "Responsibilities:\n"
    "- Design full-stack web applications using Angular and .NET Core\n"
    "- Write clean, testable code following SOLID principles\n"
    "- Participate in code reviews and sprint planning\n"
)
